#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE nyx_venatrix;
    CREATE DATABASE saturnus;
    GRANT ALL PRIVILEGES ON DATABASE nyx_venatrix TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE saturnus TO $POSTGRES_USER;
EOSQL
